# **データベース処理(Googledriveからローカルに落とす)**

In [24]:
import os
import gdown

# 食事行動データベースの設定
# Google スプレッドシート: https://docs.google.com/spreadsheets/d/1AmSBnOUhCBBBjP-9AOESp_lpT3bNK-iK/edit
data_path = "./downloaded_folder/食事行動データベース.xlsx"

# データベース保存先フォルダを作成
os.makedirs(os.path.dirname(data_path), exist_ok=True)

# Google Driveから食事行動データベースをダウンロード
# 注意: 実際のファイルIDは、Googleスプレッドシートをエクスポートした際のIDに置き換える必要があります
database_file_id = "1AmSBnOUhCBBBjP-9AOESp_lpT3bNK-iK"  # スプレッドシートのID

try:
    # スプレッドシートをExcel形式でダウンロード
    url = f"https://docs.google.com/spreadsheets/d/{database_file_id}/export?format=xlsx"
    gdown.download(url, data_path, quiet=False, fuzzy=True)
    print(f"食事行動データベースのダウンロードが完了しました: {data_path}")
except Exception as e:
    print(f"ダウンロードエラー: {e}")
    print("手動でスプレッドシートをExcel形式でダウンロードし、指定のパスに保存してください。")

Downloading...
From: https://docs.google.com/spreadsheets/d/1AmSBnOUhCBBBjP-9AOESp_lpT3bNK-iK/export?format=xlsx
To: /home/tsukagoshitoshihiro/workspace/ICASSP/Semi_supervise/prepare/downloaded_folder/食事行動データベース.xlsx
154kB [00:00, 870kB/s]

食事行動データベースのダウンロードが完了しました: ./downloaded_folder/食事行動データベース.xlsx

In [7]:
import pandas as pd
data_path = "./downloaded_folder/食事行動データベース.xlsx"
output_folder = "./downloaded_folder/behavior"

#ファイル階層は以下を想定
#
# behavior(output_folder)
#    |
#    |--text_ful
#    |     |--MYN01_ful.txt
#    |      --MCN01_ful.txt
#     --  wav_ful
#          |--MYN01_ful.wav
#           --MCN01_ful.wav
#

database = pd.ExcelFile(data_path)

input_sheet_name = database.sheet_names
#シート名を確認
print(input_sheet_name)

['高齢者（口腔機能検査）', '若年者（口腔機能検査）', '高齢者（データパス）', '若年者（データパス）']

In [8]:
#DataFrameとして'若年者（データパス）'を読込み
young_person_df = database.parse(input_sheet_name[3])
#読み込んだシートの先頭10行を表示
young_person_df.head(5)

,ID,カメラ,Unnamed: 2,Unnamed: 3,重量,加速度,Unnamed: 6,Unnamed: 7,ラベル,Unnamed: 9,音声,Unnamed: 11
0,NaN,1(正面),2(上),3(横),NaN,頭,左,右,timing,txt,NaN,NaN
1,NaN,1(正面),2(上),3(横),NaN,頭,左,右,timing,txt,NaN,NaN
2,MYN01,https://drive.google.com/file/d/1aNmw6D5gRfNlv...,https://drive.google.com/file/d/1lGXcA8PUJp8Lq...,https://drive.google.com/file/d/1les49eSdK3lTz...,https://drive.google.com/file/d/1BTC9To3aoklEz...,https://drive.google.com/file/d/16ccESQIQ7F_q9...,https://drive.google.com/file/d/1aIaQvtiiE4ykv...,https://drive.google.com/file/d/1NwR2GfKJ-NnDl...,https://drive.google.com/file/d/1aZt5mJY8DJIBM...,https://drive.google.com/file/d/15qzuV5oKQpoTj...,https://drive.google.com/file/d/1DokBN8c7lg8WF...,MYN01
3,MCN01,https://drive.google.com/file/d/1MTtXhlM64exaQ...,https://drive.google.com/file/d/1F3e_65aw4JP3l...,https://drive.google.com/file/d/11czyh2JJjd_N6...,https://drive.google.com/file/d/1PUW1amLNZ_Keb...,https://drive.google.com/file/d/1vtVZWUqF-dyFg...,https://drive.google.com/file/d/1p8Hc4vWrx5KxU...,https://drive.google.com/file/d/1e_Ht9Rn_jBNHJ...,https://drive.google.com/file/d/1rf4O3a1kbqkRK...,https://drive.google.com/file/d/11wPGdByBsKx6V...,https://drive.google.com/file/d/1ApBEnesuwgD1B...,MCN01
4,MYT01,https://drive.google.com/file/d/1UFqqGx0Y4SQDU...,https://drive.google.com/file/d/1amXZA7U2eSD0T...,https://drive.google.com/file/d/1T9wAiJj4Oor2I...,https://drive.google.com/file/d/1FY1JnLA8w1atV...,https://drive.google.com/file/d/1pLdpGS_SHjdb2...,https://drive.google.com/file/d/1eGh3Gz_Bq8-7L...,https://drive.google.com/file/d/1a6Je5oXdLryD8...,https://drive.google.com/file/d/1r9gatyxcYmHQg...,https://drive.google.com/file/d/1E6-3bQlxp9Yqk...,https://drive.google.com/file/d/1nnSN7vJdDTwZm...,MYT01

ラベル付け替え

In [9]:
young_person_df= young_person_df.rename(columns={young_person_df.columns[1]: 'カメラ(正面)',
                                                 young_person_df.columns[2]: 'カメラ(上)',
                                                 young_person_df.columns[3]: 'カメラ(横)',
                                                 young_person_df.columns[5]: '加速度(頭)',
                                                 young_person_df.columns[6]: '加速度(左)',
                                                 young_person_df.columns[7]: '加速度(右)',
                                                 young_person_df.columns[8]: 'timestamp',
                                                 young_person_df.columns[9]: 'timing'})
young_person_df=young_person_df.drop(young_person_df.index[[0,1]])
#確認
young_person_df.head(5)

,ID,カメラ(正面),カメラ(上),カメラ(横),重量,加速度(頭),加速度(左),加速度(右),timestamp,timing,音声,Unnamed: 11
2,MYN01,https://drive.google.com/file/d/1aNmw6D5gRfNlv...,https://drive.google.com/file/d/1lGXcA8PUJp8Lq...,https://drive.google.com/file/d/1les49eSdK3lTz...,https://drive.google.com/file/d/1BTC9To3aoklEz...,https://drive.google.com/file/d/16ccESQIQ7F_q9...,https://drive.google.com/file/d/1aIaQvtiiE4ykv...,https://drive.google.com/file/d/1NwR2GfKJ-NnDl...,https://drive.google.com/file/d/1aZt5mJY8DJIBM...,https://drive.google.com/file/d/15qzuV5oKQpoTj...,https://drive.google.com/file/d/1DokBN8c7lg8WF...,MYN01
3,MCN01,https://drive.google.com/file/d/1MTtXhlM64exaQ...,https://drive.google.com/file/d/1F3e_65aw4JP3l...,https://drive.google.com/file/d/11czyh2JJjd_N6...,https://drive.google.com/file/d/1PUW1amLNZ_Keb...,https://drive.google.com/file/d/1vtVZWUqF-dyFg...,https://drive.google.com/file/d/1p8Hc4vWrx5KxU...,https://drive.google.com/file/d/1e_Ht9Rn_jBNHJ...,https://drive.google.com/file/d/1rf4O3a1kbqkRK...,https://drive.google.com/file/d/11wPGdByBsKx6V...,https://drive.google.com/file/d/1ApBEnesuwgD1B...,MCN01
4,MYT01,https://drive.google.com/file/d/1UFqqGx0Y4SQDU...,https://drive.google.com/file/d/1amXZA7U2eSD0T...,https://drive.google.com/file/d/1T9wAiJj4Oor2I...,https://drive.google.com/file/d/1FY1JnLA8w1atV...,https://drive.google.com/file/d/1pLdpGS_SHjdb2...,https://drive.google.com/file/d/1eGh3Gz_Bq8-7L...,https://drive.google.com/file/d/1a6Je5oXdLryD8...,https://drive.google.com/file/d/1r9gatyxcYmHQg...,https://drive.google.com/file/d/1E6-3bQlxp9Yqk...,https://drive.google.com/file/d/1nnSN7vJdDTwZm...,MYT01
5,MTI01,https://drive.google.com/file/d/1mc9wjrCvXRoe3...,https://drive.google.com/file/d/1Z08ZOrrelgGaI...,https://drive.google.com/file/d/1m-_mBkW246U7B...,https://drive.google.com/file/d/1m16vF5aIDmjpm...,https://drive.google.com/file/d/1lYrvEG07OIxeE...,https://drive.google.com/file/d/1rvkWz7QJnzK4Y...,https://drive.google.com/file/d/1jdJNXlrkdJ_0Z...,https://drive.google.com/file/d/1kF5uz68H-RapY...,https://drive.google.com/file/d/1L1h5HtHBMtcg6...,https://drive.google.com/file/d/1Ccy_N05lR3eWb...,MTI01
6,MTM01,https://drive.google.com/file/d/1jzViQ0aW3sEJJ...,https://drive.google.com/file/d/1mVSihOgmJ8pfz...,https://drive.google.com/file/d/1f0dee_X04Pakg...,https://drive.google.com/file/d/11U1I_Tj1CRiyC...,https://drive.google.com/file/d/12Rxc-uhAV3HFl...,https://drive.google.com/file/d/1EYmw2hL9gcRXa...,https://drive.google.com/file/d/1U1IGm0KD7OcYg...,https://drive.google.com/file/d/19ssfB2C99nrBx...,https://drive.google.com/file/d/1W2peJ7wXBO2xd...,https://drive.google.com/file/d/1ekhCUR_9HyVIC...,MTM01

話者ID、発話タイミングラベル、音声データのパスのみを抽出し、全てNanの行を排除

In [10]:
young_person_df=young_person_df.loc[:,['ID','timing','音声']]
young_person_df=young_person_df.dropna(how='all')
young_person_df=young_person_df.reset_index()
young_person_df.head(5)

,index,ID,timing,音声
0,2,MYN01,https://drive.google.com/file/d/15qzuV5oKQpoTj...,https://drive.google.com/file/d/1DokBN8c7lg8WF...
1,3,MCN01,https://drive.google.com/file/d/11wPGdByBsKx6V...,https://drive.google.com/file/d/1ApBEnesuwgD1B...
2,4,MYT01,https://drive.google.com/file/d/1E6-3bQlxp9Yqk...,https://drive.google.com/file/d/1nnSN7vJdDTwZm...
3,5,MTI01,https://drive.google.com/file/d/1L1h5HtHBMtcg6...,https://drive.google.com/file/d/1Ccy_N05lR3eWb...
4,6,MTM01,https://drive.google.com/file/d/1W2peJ7wXBO2xd...,https://drive.google.com/file/d/1ekhCUR_9HyVIC...

フォルダ作成

In [11]:
import os

wav_full_path = output_folder + "/wav_ful"
# フォルダが既に存在するか確認
if not os.path.exists(wav_full_path):
# フォルダが存在しない場合、階層ごとにフォルダを作成
    os.makedirs(wav_full_path)
    print(f"フォルダを作成しました: {wav_full_path}")
else:
    print(f"フォルダは既に存在します: {wav_full_path}")

text_full_path = output_folder + "/text_ful"
# フォルダが既に存在するか確認
if not os.path.exists(text_full_path):
# フォルダが存在しない場合、階層ごとにフォルダを作成
    os.makedirs(text_full_path)
    print(f"フォルダを作成しました: {text_full_path}")
else:
    print(f"フォルダは既に存在します: {text_full_path}")

フォルダは既に存在します: ./downloaded_folder/behavior/wav_ful
フォルダは既に存在します: ./downloaded_folder/behavior/text_ful

発話タイミングラベルをGoogedriveからダウンロード

In [16]:
import subprocess
from tqdm import tqdm
import warnings

# UserWarningを無視する
warnings.filterwarnings("ignore", category=UserWarning)

# 成功と失敗を追跡するリスト
success_downloads = []
failed_downloads = []

for i in tqdm(range(len(young_person_df.ID)), desc="ダウンロード進捗"):
    speaker = young_person_df.ID[i]
    url = young_person_df.timing[i]
    url_ID = url.split("/")
    text_url_ID = url_ID[5]
    
    text_destination = text_full_path+"/"+speaker+"_full.txt"
    
    # gdownコマンドの構築
    command = f"gdown https://drive.google.com/uc?id={text_url_ID} -O {text_destination}"
        
    # コマンドの実行（標準出力と標準エラー出力を抑制）
    result = subprocess.run(command, shell=True)
    #, check=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE
    

    # 結果に基づいてリストを更新
    if result.returncode == 0:
        success_downloads.append(text_destination)
    else:
        failed_downloads.append(text_destination)

# 警告のフィルタリングを元に戻す
warnings.filterwarnings("default", category=UserWarning)

# 成功と失敗の結果を表示
print(f"\nダウンロード成功: {len(success_downloads)}件")
#for file in success_downloads:
    #print(f"成功: {file}")

print(f"\nダウンロード失敗: {len(failed_downloads)}件")
for file in failed_downloads:
    print(f"失敗: {file}")

ダウンロード進捗:   0%|          | 0/55 [00:00<?, ?it/s]Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=15qzuV5oKQpoTjkeamz9-qqwCjBMPbedH

but Gdown can't. Please check connections and permissions.
ダウンロード進捗:   2%|▏         | 1/55 [00:08<08:00,  8.89s/it]Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=11wPGdByBsKx6VRQMzUdY3D4vrxKuCNXp

but Gdown can't. Please check connections and permissions.
ダウンロード進捗:   4%|▎         | 2/55 [00:18<08:06,  9.18s/it]Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=1E6-3bQlxp9YqkEnPZlN--raDSrWULf-k

but Gdown can't. Please check connections and permissions.
ダウンロード進捗:   5%|▌         | 3/55 [00:28<08:18,  9.60s/it]Traceback (most recent call last):
  File "/home/tsukagoshitoshihiro/.pyenv/versions/apsipa/bin/gdown", line 8, in <module>
    sys.exit(main())
  File "/home/tsukagoshitoshihiro/.pyenv/versions/3.10.5/envs/apsipa/lib/python3.10/site-packages/gdown/__main__.py", line 172, in main
    download(
  File "/home/tsukagoshitoshihiro/.pyenv/versions/3.10.5/envs/apsipa/lib/python3.10/site-packages/gdown/download.py", line 202, in download
    res = sess.get(url, stream=True, verify=verify)
  File "/home/tsukagoshitoshihiro/.pyenv/versions/3.10.5/envs/apsipa/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/tsukagoshitoshihiro/.pyenv/versions/3.10.5/envs/apsipa/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tsukagoshitoshihiro/.pyenv/versions/3.10.5/envs/apsipa/lib/python3.10/site-packages/requests/sessions.py", line 724, in send
    history = [resp for resp in gen]
  File "/home/tsukagoshitoshihiro/.pyenv/versions/3.10.5/envs/apsipa/lib/python3.10/site-packages/requests/sessions.py", line 724, in <listcomp>
    history = [resp for resp in gen]
  File "/home/tsukagoshitoshihiro/.pyenv/versions/3.10.5/envs/apsipa/lib/python3.10/site-packages/requests/sessions.py", line 265, in resolve_redirects
    resp = self.send(
  File "/home/tsukagoshitoshihiro/.pyenv/versions/3.10.5/envs/apsipa/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/tsukagoshitoshihiro/.pyenv/versions/3.10.5/envs/apsipa/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/tsukagoshitoshihiro/.pyenv/versions/3.10.5/envs/apsipa/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/home/tsukagoshitoshihiro/.pyenv/versions/3.10.5/envs/apsipa/lib/python3.10/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
  File "/home/tsukagoshitoshihiro/.pyenv/versions/3.10.5/envs/apsipa/lib/python3.10/site-packages/urllib3/connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
  File "/home/tsukagoshitoshihiro/.pyenv/versions/3.10.5/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/home/tsukagoshitoshihiro/.pyenv/versions/3.10.5/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/home/tsukagoshitoshihiro/.pyenv/versions/3.10.5/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/tsukagoshitoshihiro/.pyenv/versions/3.10.5/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/home/tsukagoshitoshihiro/.pyenv/versions/3.10.5/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/home/tsukagoshitoshihiro/.pyenv/versions/3.10.5/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt
ダウンロード進捗:   5%|▌         | 3/55 [00:30<08:42, 10.05s/it]

KeyboardInterrupt:

# **フル尺の音声ファイルをGoogledriveからダウンロード**　
##### (アクセス制限がかかるとエラーが発生する。少し時間を待ってもう一度試そう)

In [8]:
import os
import subprocess
from tqdm import tqdm
import warnings
import sys

success_list_wav = output_folder + "/success_list_wav.txt"

# 成功したダウンロードのリストを保存する関数
def save_success_list(success_downloads):
    with open(success_list_wav, 'w') as f:
        for item in success_downloads:
            f.write("%s\n" % item)

# 成功したダウンロードのリストを読み込む関数
def load_success_list():
    try:
        with open(success_list_wav, 'r') as f:
            return [line.strip() for line in f]
    except FileNotFoundError:
        print("Fileが見つかりません")
        return []



# 既にダウンロードされたファイルのリストを読み込む
success_downloads = load_success_list()

# UserWarningを無視する
warnings.filterwarnings("ignore", category=UserWarning)

failed_downloads = []

for i in tqdm(range(len(young_person_df.ID)), desc="ダウンロード進捗"):
    speaker = young_person_df.ID[i]
    wav_destination = f"{wav_full_path}/{speaker}_full.wav"
    
    if wav_destination in success_downloads:
        print(f"{wav_destination} は既にダウンロードされています。スキップします。")
        continue
    
    url = young_person_df.音声[i]
    url_ID = url.split("/")[-2]  # URLからIDを抽出
    command = f"gdown https://drive.google.com/uc?id={url_ID} -O {wav_destination}"
    
    result = subprocess.run(command, shell=True, check=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    
    if result.returncode == 0:
        success_downloads.append(wav_destination)
    else:
        print(f"ダウンロード失敗: {wav_destination}")
        print("エラーメッセージ:", result.stderr.decode('utf-8'))
        save_success_list(success_downloads)  # 現在の成功リストを保存
        sys.exit(f"エラーによりプログラムを終了します。(時間を経過させて再度実行してください)")

# 警告のフィルタリングを元に戻す設定
warnings.filterwarnings("default", category=UserWarning)

# 成功と失敗の結果を表示
print(f"\nダウンロード成功: {len(success_downloads)}件")
print(f"\nダウンロード失敗: {len(failed_downloads)}件")

# 成功したダウンロードのリストを保存
save_success_list(success_downloads)

ダウンロード進捗:   0%|          | 0/55 [00:00<?, ?it/s]

./downloaded_folder/behavior/wav_ful/MYN01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MCN01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MYT01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MTI01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MTM01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MRO01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MKH01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MKS01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MRM01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MAO01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MYM01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MTF01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MKH02_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MKN01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MMT01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MHT01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MKJ01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MKM01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MHS01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MYY01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MTS01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MSS01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MMM01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MRY01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MAY01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MHY01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FMT01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MTH01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MAM01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MMT02_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FKM01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FSK01_full.wav は既にダウンロードされています。スキップします。

ダウンロード進捗: 100%|██████████| 55/55 [13:26<00:00, 14.65s/it]

ダウンロード成功: 55件

ダウンロード失敗: 0件

## 高齢者も同様に実施

In [12]:
#DataFrameとして'若年者（データパス）'を読込み
young_person_df = database.parse(input_sheet_name[2])
#読み込んだシートの先頭10行を表示
young_person_df.head(5)

young_person_df= young_person_df.rename(columns={young_person_df.columns[1]: 'カメラ(正面)',
                                                 young_person_df.columns[2]: 'カメラ(上)',
                                                 young_person_df.columns[3]: 'カメラ(横)',
                                                 young_person_df.columns[5]: '加速度(頭)',
                                                 young_person_df.columns[6]: '加速度(左)',
                                                 young_person_df.columns[7]: '加速度(右)',
                                                 young_person_df.columns[8]: 'timestamp',
                                                 young_person_df.columns[9]: 'timing'})
young_person_df=young_person_df.drop(young_person_df.index[[0,1]])
#確認
young_person_df.head(5)
young_person_df=young_person_df.loc[:,['ID','timing','音声']]
young_person_df=young_person_df.dropna(how='all')
young_person_df=young_person_df.reset_index()
young_person_df.head(5)

,index,ID,timing,音声
0,2,MHK01,https://drive.google.com/file/d/12_wsLobqxbZCG...,https://drive.google.com/file/d/1ZMjY5duYc_hyZ...
1,3,MYT02,https://drive.google.com/file/d/1kn7y71kGmXRCV...,https://drive.google.com/file/d/1Ps6x_xd4A7s-J...
2,4,FEI01,https://drive.google.com/file/d/1QRkq7IZLf_UHh...,https://drive.google.com/file/d/1lxfUHlwoJwrfR...
3,5,MMA01,https://drive.google.com/file/d/1QjJQKL1aBiQ2K...,https://drive.google.com/file/d/1Xbv1o1ANSMans...
4,6,MTI02,https://drive.google.com/file/d/168lmN7W3iaJnu...,https://drive.google.com/file/d/1BQGndhWEITQ6u...

In [13]:
import os
import subprocess
from tqdm import tqdm
import warnings
import sys

success_list_wav = output_folder + "/success_list_wav.txt"

# 成功したダウンロードのリストを保存する関数
def save_success_list(success_downloads):
    with open(success_list_wav, 'w') as f:
        for item in success_downloads:
            f.write("%s\n" % item)

# 成功したダウンロードのリストを読み込む関数
def load_success_list():
    try:
        with open(success_list_wav, 'r') as f:
            return [line.strip() for line in f]
    except FileNotFoundError:
        print("Fileが見つかりません")
        return []



# 既にダウンロードされたファイルのリストを読み込む
success_downloads = load_success_list()

# UserWarningを無視する
warnings.filterwarnings("ignore", category=UserWarning)

failed_downloads = []

for i in tqdm(range(len(young_person_df.ID)), desc="ダウンロード進捗"):
    speaker = young_person_df.ID[i]
    wav_destination = f"{wav_full_path}/{speaker}_full.wav"
    
    if wav_destination in success_downloads:
        print(f"{wav_destination} は既にダウンロードされています。スキップします。")
        continue
    
    url = young_person_df.音声[i]
    url_ID = url.split("/")[-2]  # URLからIDを抽出
    command = f"gdown https://drive.google.com/uc?id={url_ID} -O {wav_destination}"
    
    result = subprocess.run(command, shell=True, check=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    
    if result.returncode == 0:
        success_downloads.append(wav_destination)
    else:
        print(f"ダウンロード失敗: {wav_destination}")
        print("エラーメッセージ:", result.stderr.decode('utf-8'))
        save_success_list(success_downloads)  # 現在の成功リストを保存
        sys.exit(f"エラーによりプログラムを終了します。(時間を経過させて再度実行してください)")

# 警告のフィルタリングを元に戻す設定
warnings.filterwarnings("default", category=UserWarning)

# 成功と失敗の結果を表示
print(f"\nダウンロード成功: {len(success_downloads)}件")
print(f"\nダウンロード失敗: {len(failed_downloads)}件")

# 成功したダウンロードのリストを保存
save_success_list(success_downloads)

ダウンロード進捗:   0%|          | 0/63 [00:00<?, ?it/s]

./downloaded_folder/behavior/wav_ful/MHK01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MYT02_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FEI01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MMA01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MTI02_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MMM02_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FYN02_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MTK01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MKF01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MKS02_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FJK01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FFY01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FEK01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FKK01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FMT02_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FMY02_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FKS02_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MSK01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MSK02_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MTM02_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MMY01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MSK03_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MMT03_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MHH01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FKY01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MHH02_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MMT04_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MTK02_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MTU01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MSH01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FKY02_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MYK02_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FKS03_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FMK01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MSH02_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MTH02_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FMA01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FNH01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FKM03_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FSK02_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FKY03_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MHI01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MNN01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FKN01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FEU01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FKH01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FYO01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MAT01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MYA01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FHO02_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FIS01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FKS04_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FMY03_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FYO02_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/FST01_full.wav は既にダウンロードされています。スキップします。
./downloaded_folder/behavior/wav_ful/MYO01_full.wav は既にダウンロードされています。スキップします。

ダウンロード進捗:  89%|████████▉ | 56/63 [00:01<00:00, 50.93it/s]

ダウンロード失敗: ./downloaded_folder/behavior/wav_ful/FYT02_full.wav
エラーメッセージ: Failed to retrieve file url:

	Too many users have viewed or downloaded this file recently. Please
	try accessing the file again later. If the file you are trying to
	access is particularly large or is shared with many people, it may
	take up to 24 hours to be able to view or download the file. If you
	still can't access a file after 24 hours, contact your domain
	administrator.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=10IzxnEoeOinO6aU4EMoEi1yms5OlnQNT

but Gdown can't. Please check connections and permissions.

SystemExit: エラーによりプログラムを終了します。(時間を経過させて再度実行してください)